
// get all customers
//GET http://localhost:3000/customers HTTP/1.1

###

//create user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{"customerName":"Anne Jensen", "email":"anne@gmail.com", "password":"annespassword", "basket": []}

###


// get customer by id
GET http://localhost:3000/users/anne@gmail.com HTTP/1.1

###

// login user
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{"email":"anne@gmail.com", "password": "annespassword"}


###

// put item in basket for specific user
PUT http://localhost:3000/users/anne@gmail.com/basket HTTP/1.1
content-type: application/json

{ 
 "item":"new-cosrx-combined-cream-pure-fit-cica"
}

// delete item in basket for specific user
DELETE http://localhost:3000/users/anne@gmail.com/basket HTTP/1.1
content-type: application/json

{ 
 "item":"new-cosrx-combined-cream-pure-fit-cica"
}

###

//get basket of specific user
GET http://localhost:3000/users/anne@gmail.com/basket HTTP/1.1

###

// get products
GET http://localhost:3000/products HTTP/1.1

###


// get product by id
GET http://localhost:3000/products/new-cosrx-combined-cream-pure-fit-cica HTTP/1.1

###

// get product by category
GET http://localhost:3000/products/categories/combined HTTP/1.1

###

// get categories
GET http://localhost:3000/categories HTTP/1.1

###


// get categories by id
GET http://localhost:3000/categories/skintype HTTP/1.1

###
