import { Product } from "./product.js";

export function getProductsIndex() {
    //create array of products
    //name, price, listOfTags, description, imageURL
    let list = [
        new Product(
            "Cosrx - Pure Fit Cica Cream",
            "219 dkk",
            "cosrx-combined-cream-pure-fit-cica-new",
            "Moisturising face cream that minimizes impurities, redness and acne scars",
            "images\products\cosrx-combined-cream-cosrx_-_pure_fit_cica_cream.jpg"
        ),
        new Product(
            "Cosrx - Balancium Comfort Ceramide Soft Cream Sheet Mask",
            "169 dkk",
            "cosrx-combined-dry-mask-balancium-comfort-ceramide-soft",
            "Description here",
            "images\products\cosrx-combined-dry-mask-cosrx_-_balancium_comfort_ceramide_soft_cream_sheet_mask.jpg",
        ),
        new Product(
            "Cosrx - Hydrium Triple Hyaluronic Water Wave Sheet Mask",
            "169 dkk",
            "cosrx-combined-dry-mask-hydrium-triple-hyaloronic-water-wave-sheet-discount",
            "Description here",
            "images\products\cosrx-combined-dry-mask-cosrx_-_hydrium_triple_hyaluronic_water_wave_sheet_mask.jpg",
        ),
        new Product(
            "Cosrx - Ultimate Nourishing Rice Overnight Mask",
            "169 dkk",
            "cosrx-combined-dry-mask-ultimate-nourishing-rice-overnight",
            "Description here",
            "images\products\cosrx-combined-dry-mask-cosrx_-_ultimate_nourishing_rice_overnight_mask.jpg",
        ),
        new Product(
            "Cosrx - Full Fit Propolis Synergy Toner",
            "169 dkk",
            "cosrx-combined-dry-toner-full-fit-propolis-synergy-new",
            "Description here",
            "images\products\cosrx-combined-dry-toner-cosrx_-_full_fit_propolis_synergy_toner.jpg",
        ),
        new Product(
            "Cosrx - Low pH Good Morning Gel Cleanser",
            "169 dkk",
            "cosrx-combined-sensitive-cleanser-low-ph-good-morning-gel",
            "Description here",
            "images\products\cosrx-combined-sensitive-cleanser-cosrx_-_low_pH_good_morning_gel_cleanser.jpg",
        ),
        new Product(
            "Cosrx - Hydrium Centella Aqua Soothing Ampoule",
            "169 dkk",
            "cosrx-combined-serum-hydrium-centella-aqua-soothing-ampoule-discount",
            "Description here",
            "images\products\cosrx-combined-serum-cosrx_-_hydrium_centella_aqua_soothing_ampoule.jpg",
        ),
        new Product(
            "Cosrx - Pure Fit Cica Toner",
            "169 dkk",
            "cosrx-combined-toner-pure-fit-cica",
            "Description here",
            "images\products\cosrx-combined-toner-cosrx_-_pure_fit_cica_toner.jpg",
        ),
        new Product(
            "Cosrx - Hydrium Triple Hyaluronic Moisturizing Cleanser",
            "169 dkk",
            "cosrx-dry-cleanser-hydrium-triple-hyaluronic-moisturizing",
            "Description here",
            "images\products\cosrx-dry-cleaner-cosrx_-_hydrium_triple_hyaluronic_moisturizing_cleanser.jpg",
        ),
        new Product(
            "Cosrx - Advanced Snail Mucin Gel Cleanser",
            "169 dkk",
            "cosrx-dry-cleanser-advanced-snail-mucin-gel",
            "Description here",
            "images\products\cosrx-dry-cleanser-cosrx_-_advanced_snail_mucin_gel_cleanser.jpg",
        ),
        new Product(
            "Cosrx - Propolis Light Ampoule",
            "169 dkk",
            "cosrx-dry-serum-propolis-light-ampoule",
            "Description here",
            "images\products\cosrx-dry-serum-cosrx_-_propolis_light_ampoule.jpg",
        ),
        new Product(
            "Cosrx - Green Tea Aqua Soothing Gel Cream",
            "169 dkk",
            "cosrx-oily-combined-cream-green-tea-aqua-soothing-gel",
            "Description here",
            "images\products\cosrx-oily-combined-cream-cosrx_-_green_tea_aqua_soothing_gel_cream.jpg",
        ),
        new Product(
            "Cosrx - Pure Fit Cica Cleanser",
            "169 dkk",
            "cosrx-oily-combined-cleanser-pure-fit-cica",
            "Description here",
            "images\products\cosrx-oily-combined-dry-cleanser-cosrx_-_pure_fit_cica_cleanser.jpg",
        ),
        new Product(
            "Cosrx - AC Collection Lightweight Soothing Moisturizer",
            "169 dkk",
            "cosrx-oily-cream-cosrx-ac-collection-lightweight-soothing-moisturizer",
            "Description here",
            "images\products\cosrx-oily-cream-cosrx_-_ac_collection_lightweight_soothing_moisturezer.jpg",
        ),
        new Product(
            "Cosrx - Pure Fit Cica Serum",
            "169 dkk",
            "cosrx-oily-sensitive-combined-serum-pure-fit-cica",
            "Description here",
            "images\products\cosrx-oily-sensitiv-combined-serum-cosrx_-_pure_fit_cica_serum.jpg",
        ),
        new Product(
            "Cosrx - Hydrium Watery Toner",
            "169 dkk",
            "cosrx-sensitive-combined-dry-toner-hydrium-watery",
            "Description here",
            "images\products\cosrx-sensitive-combined-dry-toner-cosrx_-_hydrium_watery_toner.jpg",
        ),
        new Product(
            "Cosrx - AHA/BHA Vitamin C Daily Toner",
            "169 dkk",
            "cosrx-sensitive-combined-toner-aha-bha-vitamin-c-daily-toner",
            "Description here",
            "images\products\cosrx-sensitive-combined-toner-cosrx_-_aha_bha_vitamin_c_daily_toner.jpg",
        ),
        new Product(
            "Cosrx - Advanced Snail 92 All In One Cream",
            "169 dkk",
            "cosrx-sensitive-cream-advanced-snail-92-all-in-one",
            "Description here",
            "images\products\cosrx-sensitive-cream-cosrx_-_advanced_snail_92_all_in_one_cream.jpg",
        ),
        new Product(
            "Cosrx - Hyaluronic Acid Intensive Cream",
            "169 dkk",
            "cosrx-sensitive-cream-hyaluronic-acid-intensive",
            "Description here",
            "images\products\cosrx-sensitive-cream-cosrx_-_hyaluronic_acid_intensive_cream.jpg",
        ),
        new Product(
            "Cosrx - Hydrium Moisture Power Enriched Cream",
            "169 dkk",
            "cosrx-sensitive-dry-cream-hydrium-moisture-power-enriched",
            "Description here",
            "images\products\cosrx-sensitive-dry-cream-cosrx_-_hydrium_moisture_power_enriched_cream.jpg",
        ),
        new Product(
            "Cosrx - Propolis Honey Overnight Mask",
            "169 dkk",
            "cosrx-sensitive-mask-propolis-honey-overnight",
            "Description here",
            "images\products\cosrx-sensitive-mask-cosrx_-_propolis_honey_overnight_mask.jpg",
        ),
        new Product(
            "Dr. Jart+ - Cicapair Calming Mask",
            "169 dkk",
            "drjart-combined-mask-cicapair-calming-sheet-new",
            "Description here",
            "images\products\drjart-combined-mask-dr_jart_-_cicapair_calming_mask.jpg",
        ),
        new Product(
            "Dr. Jart+ - Cicapair Toner",
            "169 dkk",
            "drjart-combined-toner-cicapair",
            "Description here",
            "images\products\drjart-combined-toner-dr_jart_-_cicapair_toner.jpg",
        ),
        new Product(
            "Dr. Jart+ - Intra Jet Firming Solution",
            "169 dkk",
            "drjart-dry-mask-intra-jet-firming-solution-sheet",
            "Description here",
            "images\products\drjart-dry-mask-dr_jart_-_intra_jet_firming_solution.jpg",
        ),
        new Product(
            "Dr. Jart+ - Cicapair Calming Gel Cream.",
            "169 dkk",
            "drjart-oily-cream-cicapair-calming-gel",
            "Description here",
            "images\products\drjart-oily-cream-dr_jart_-_cicapair_cicapair_calming_gel_cream.jpg",
        ),
        new Product(
            "Dr. Jart+ - Cicapair Toner",
            "169 dkk",
            "drjart-oily-toner-cicapair",
            "Description here",
            "images\products\drjart-oily-toner-dr_jart_-_cicapair_toner.jpg",
        ),
        new Product(
            "Mizon - Acence Anti Blemish Foam Cleanser",
            "169 dkk",
            "mizon-combined-cleanser-acence-anti-blemish-foam-new",
            "Description here",
            "images\products\mizon-combined-cleanser-mizon_-_acence_anti_blemish_foam_cleanser.gif",
        ),
        new Product(
            "Mizon - Black Snail All In One Cream",
            "169 dkk",
            "mizon-combined-cream-black-snail-all-in-one-cream",
            "Description here",
            "images\products\mizon-combined-cream-mizon_-_black_snail_all_in_one_cream.jpg",
        ),
        new Product(
            "Mizon - Snail Repair Intensive Toner",
            "169 dkk",
            "mizon-combined-dry-toner-snail-repair-intensive",
            "Description here",
            "images\products\mizon-combined-dry-toner-mizon_-_snail_repair_intensive_toner.jpg",
        ),
        new Product(
            "Mizon - Joyful Time Essence Mask - Aloe",
            "169 dkk",
            "mizon-combined-mask-joyful-essence-aloe-sheet",
            "Description here",
            "images\products\mizon-combined-mask-mizon_-_joyful_time_essence_mask_-_aloe.jpg",
        ),
        new Product(
            "Mizon - Collagen Power Firming Enriched Cream",
            "169 dkk",
            "mizon-dry-cream-collagen-power-firming-enriched",
            "Description here",
            "images\products\mizon-dry-cream-mizon_-_collagen_power_firming_enriched_cream.jpg",
        ),
        new Product(
            "Mizon - Joyful Time Essence Mask - Hyaluronic Acid",
            "169 dkk",
            "mizon-dry-mask-joyful-time-essence-hyaluronic-acid-sheet",
            "Description here",
            "images\products\mizon-dry-mask-mizon_-_joyful_time_essence_mask_-_hyaluronic_acid.jpg",
        ),
        new Product(
            "Mizon - Snail Repair Intensive Ampoule",
            "169 dkk",
            "mizon-dry-serum-snail-repair-intensive-ampoule",
            "Description here",
            "images\products\mizon-dry-serum-mizon_-_snail_repair_intensive_ampoule.jpg",
        ),
        new Product(
            "Mizon - Collagen Power Lifting Toner",
            "169 dkk",
            "mizon-dry-toner-collagen-power-lifting",
            "Description here",
            "images\products\mizon-dry-toner-mizon_-_collagen_power_lifting_toner.jpg",
        ),
        new Product(
            "Mizon - All In One Snail Repair Cream",
            "169 dkk",
            "mizon-oily-combined-cream-all-in-one-snail-repair",
            "Description here",
            "images\products\mizon-oily-combined-cream-mizon_-_all_in_one_snail_repair_cream.jpg",
        ),
        new Product(
            "Mizon - AHA 8% Peeling Serum",
            "169 dkk",
            "mizon-oily-combined-serum-aha-8-%-percent-peeling",
            "Description here",
            "images\products\mizon-oily-combined-serum-mizon_aha_8procent_peeling_serum.jpg",
        ),
        new Product(
            "Mizon - Snail Recovery Gel Cream",
            "169 dkk",
            "mizon-oily-sensitive-combined-cream-snail-recovery-gel-cream",
            "Description here",
            "images\products\mizon-oily-sensitiv-combined-cream-mizon_-_snail_recovery_gel_cream.jpg",
        ),
        new Product(
            "Mizon - Collagen Power Lifting Cream",
            "169 dkk",
            "mizon-sensitive-cream-collagen-power-lifting-discount",
            "Description here",
            "images\products\mizon-sensitive-cream-mizon_collagen_power_lifting_cream.jpg",
        ),
        new Product(
            "Mizon - Collagen 100 Serum",
            "169 dkk",
            "mizon-sensitive-dry-serum-collagen-100",
            "Description here",
            "images\products\mizon-sensitive-dry-serum-mizon_-_collagen_100_serum.jpg",
        ),
        new Product(
            "Nature Republic - Real Comforting Mask Sheet - Vitamin C",
            "169 dkk",
            "nature-republic-combined-dry-mask-real-comforting-sheet-vitamin-c",
            "Description here",
            "images\products\nature_republic-combined-dry-mask-nature_republic_-_real_comforting_mask_sheet_-_vitamin_c.jpg",
        ),
        new Product(
            "Nature Republic - Real Comforting Mask Sheet - AHA/BHA",
            "169 dkk",
            "nature-republic-combined-dry-mask-real-comforting-sheet-aha-bha",
            "Description here",
            "images\products\nature_republic-combined-mask-nature_republic_-_real_comforting_mask_sheet_-_aha_bha.jpg",
        ),
        new Product(
            "Nature Republic - Real Comforting Mask Sheet - Vitamin E",
            "169 dkk",
            "nature-republic-dry-mask-real-comforting-sheet-vitamin-e",
            "Description here",
            "images\products\nature_republic-dry-mask-nature_republic_-_real_comforting_mask_sheet_-_vitamin_e.jpg",
        )
    ]
    
    return list;
}
